import SubjectDashboard from "../../common/SubjectDashboard"
const topicOrder = [
  "NumPy",
  "Pandas",
  "Data Preprocessing",
  "Linear Regression",
  "Regression Metrics",
  "Logistic Regression",
  "Classification Metrics",
  "Decision Trees",
  "Introduction to Neural Networks",
  "Neural Networks",
  "Multi Layer Perceptron",
  "Machine Learning Model Evaluation",
  "NLP",
  "Embeddings",
  "Image Models",
  "Agentic AI",
  "Conditional Branching",
  "LangGraph",
  "Sense–Decide–Act",
  "State Management of AI Agents",
  "Prompt Evaluation",
  "Zero-Shot Prompting",
  "Uncategorized"
];

const mustReviseKeywords = [
  "Support triage agent",
  "Numpy- True False Ladder",
  "Operation on vectors",
  "Monthly Expenses",
  "Employee Salary Range and Department Count Analysis",
  "Data Preprocessing Exercise",
  "Patient Record Preprocessor",
  "Mumbai House Price Booster",
  "Data Preprocessing",
  "DataPreprocessing_Diseases",
  "Linear Regression using Sklearn",
  "Linear Regression",
  "House prediction using MLR",
  "Credit card fraud Detection",
  "Predicting the Presence of Snakes in Australia Using Logistic Regression",
  "Tumour Malignancy Classifier",
  "Confusion Matrix",
  "DT Classifier",
  "Telecom Churn Predictor",
  "Breast Cancer Diagnosis: Feature Importance",
  "Implementing different activation functions and their derivatives",
  "Train a Neural Network Using PyTorch with Different Activations",
  "Implementing a neural network from scratch using Numpy.",
  "Multi-Layer Perceptron",
  "Student Exam Registration",
  "ATM Transaction Processor",
  "Library Book Reservation",
  "Food Delivery Order Tracker",
  "Employee Leave Approver",
  "E-commerce Return Processor",
  "Hospital Appointment Scheduler",
  "Bank Loan Application Pipeline",
  "Inventory Reorder System",
  "Customer Complaint Resolver",
  "Insurance Claim Processor",
  "Embed the Excuse",
  "Movie Match",
  "Roommate Compatibility Score",
  "Spoiler or Safe?",
  "Find the Right Meme",
  "Lost & Found Board",
  "Vibe Check",
  "Odd One Out",
  "Auto Shelf",
  "Campus FAQ Bot",
  "Myth Buster",
  "Describe the Scene",
  "Expense Approval Workflow",
  "Leave Application Router",
  "UPI Fraud Detector",
  "Student Score Cross-Validator",
  "XOR Pattern Classifier",
  "Spiral Dataset Classifier",
  "Spam Email Detector — NLTK + TF-IDF + Logistic Regression",
  "Job Posting Classifier — NLP Pipeline (NLTK + TF-IDF + Naive Bayes)",
  "News Headline Classifier — CountVectorizer vs TF-IDF + Logistic Regression",
  "Language Detector — Character N-gram + Logistic Regression",
  "Product Category Tagger — TF-IDF + LinearSVC",
  "Fake News Detector — BoW + Logistic Regression",
  "Agent Evaluator",
  "Hello Tools",
  "Know When Not to Act",
  "Form Field Validator",
  "Package Shipping Calculator",
  "Critic in Chief"
];

export default function Page() {
  return <SubjectDashboard subjectName="GenAI" courseTag="GenAI" semesterTitle="Semester 4" topicOrder={topicOrder} mustReviseKeywords={mustReviseKeywords} />
}
